import type { Metadata } from "next";
import SocketProvider from "@/provider/SocketProvider";
import SimpleProvider from "@/provider/SimpleProvider";
import { Toaster } from "@/components/ui/toaster";
import localFont from "next/font/local";
import "./globals.css";
import { ParticleConnectkit } from "@/provider/ConnectKit";

const protestLocal = localFont({
  src: "./fonts/ProtestStrike-Regular.ttf",
  variable: "--font-protest-strike",
  weight: "400",
});

const spaceGroteskLocal = localFont({
  src: "./fonts/SpaceGrotesk-VariableFont_wght.ttf",
  variable: "--font-space-grotesk",
  weight: "300 400 500 600 700",
});

const playLocal = localFont({
  src: "./fonts/Play-Regular.ttf",
  variable: "--font-play",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${protestLocal.variable} ${spaceGroteskLocal.variable} ${playLocal.variable} antialiased bg-transparent font-grotesk`}
      >
        <ParticleConnectkit>
          <SimpleProvider>
            <Toaster />
            <SocketProvider>{children}</SocketProvider>
          </SimpleProvider>
        </ParticleConnectkit>
      </body>
    </html>
  );
}
